### ISSUE TITLE
some question about transfered labed

### ISSUE THREAD

**Issue by qwelongh** [LungCellAtlas/mapping_data_to_the_HLCA#5]
Hi,

I used this tool to label my data, but I noticed a cluster that appears to have been labeled as Classical Monocytes instead of Neutrophils.

<img width="1422" alt="1686790760804" src="https://github.com/LungCellAtlas/mapping_data_to_the_HLCA/assets/75315325/2ad25bcd-2d6c-44e9-8826-6ec7865bfbce">

![image](https://github.com/LungCellAtlas/mapping_data_to_the_HLCA/assets/75315325/5ffe0b66-8459-4b86-923d-2e8f14c3d064)

![image](https://github.com/LungCellAtlas/mapping_data_to_the_HLCA/assets/75315325/1f084456-08f6-42e4-8500-1aadf542eb34)

**Comment by LisaSikkema** [comment]
Hey! For some year I missed the notification for this issue and only saw it half a year later, sorry!! Probably too late now, but you're right, the HLCA doesn't include neutrophils, and as it does not have the label "neutrophil" it also cannot transfer that label to other cells. Neutrophils will therefore wrongly be labeled as other cell types. Ideally though it would do that with high uncertainty... did it?

**Comment by qwelongh** [comment]
Thank you for your response. As shown by the umap, Neutrophils have not been identified as "Unknown," indicating that they surpass the threshold set in the tutorial. This could also be due to the similarity between monocytes and Neutrophils.

**Comment by LisaSikkema** [comment]
Right I see that now. I think you're right, the scArches uncertainty metric seems to work best to identify unseen cell types when a new cell type has similarity to *multiple* other cell types, instead of being similar to only a single cell type (monocytes as you said). The metric is limited in that sense. It's good to know that it doesn't work so well for neutrophils, at least in your data but probably in other data too in that case.
